name: WorldPopulatorH
version: 0.0.1
main: fr.formiko.worldpopulatorh.WorldPopulatorHPlugin
description: Select part of the world.
author: Hydrolien
website: https://github.com/HydrolienF/WorldPopulatorH
api-version: '1.20'
commands:
  populate:
    description: Place structures and features in a selected area.
    usage: /populate
    permission: worldpopulatorh.polulate
dependencies:
  server:
    WorldSelectorH:
      load: BEFORE
      required: true