name: WorldPopulatorH
version: 0.0.1
main: fr.formiko.worldcleanerh.WorldPopulatorHPlugin
description: Select part of the world.
author: Hydrolien
website: https://github.com/HydrolienF/WorldPopulatorH
api-version: '1.20'
dependencies:
  server:
    WorldSelectorH:
      load: BEFORE
      required: true