name: $name
version: $version
main: $group.${name}Plugin
description: $description
author: Hydrolien
website: https://github.com/HydrolienF/WorldPopulatorH
api-version: "$apiVersion"
folia-supported: true

commands:
  populate:
    description: Place structures and features in a selected area.
    usage: /populate
    permission: worldpopulatorh.polulate
  populateAndClean:
    description: Place structures and features in a selected area then clean the selected area.
    usage: /populateAndClean
    permission: worldpopulatorh.polulate
dependencies:
  server:
    WorldSelectorH:
      load: BEFORE
      required: true